RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This is simple Hello World component written in Python."
ComponentDependencies:
  aws.greengrass.TokenExchangeService:
    VersionRequirement: '^2.0.0'
    DependencyType: HARD
ComponentConfiguration:
  DefaultConfiguration:
    trackerName: "Greengrass"
    units: imperial
    interval: 30
    region: us-east-1
    
Manifests:
- Platform:
    os: linux
  Artifacts:
    - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/LocationTracker.zip"
      Unarchive: ZIP
  Lifecycle:
    Install:
      Script: |-
        pip3 install gpsdclient
      Timeout: 600
    Run: "python3 -u {artifacts:decompressedPath}/LocationTracker/main.py {configuration:/trackerName} {configuration:/units} {configuration:/interval} {configuration:/region}" 
